### ISSUE TITLE
how to change invoice num: None to any other integers

### ISSUE THREAD

**Issue by moli-debugger** [by-cx/InvoiceGenerator#46]
I want to assign numbers to each of my invoice pdf. Anyone guide me to change the top text Invoice num: into any other thing

**Comment by dephekt** [comment]
It's a 3 year old issue but in case anyone sees it and doesn't know:

```python
invoice = Invoice(client=client, provider=provider, creator=creator)
invoice.number = "MY-INVOICE-23"
```

You can see all the available parameters for the invoice class in the docs: https://invoicegenerator.readthedocs.io/en/latest/modules.html#InvoiceGenerator.api.Invoice
