### ISSUE TITLE
Add image in `README.md` to show an example of invoice generated

### ISSUE THREAD

**Issue by ali-sajjad-rizavi** [by-cx/InvoiceGenerator#48]
An image will be helpful for people to have an idea what kind of invoice can be generated.

**Comment by Mohit-205** [comment]
Please provide a screenshot of the program for reference purposes

**Comment by PetrDlouhy** [comment]
In fact, I am not sure what is this issue about. The generated invoice already is in the README (maybe wasn't in the history?).
There is no "screenshot of the program", it is programming library, not a program.

Please reopen with better specification.
