### ISSUE TITLE
python 3.11, InvoiceGenerator\conf.py bug

### ISSUE THREAD

**Issue by danilovmy** [by-cx/InvoiceGenerator#50]
C:\keysbilling\Lib\site-packages\InvoiceGenerator\conf.py

```
# row 10
get_gettext(lang):
    # bla bla
    t = gettext.translation(
        # bla bla
        codeset='utf8',
        # bla bla
       )
```
gettext.translation Changed in version 3.11: codeset parameter is removed.
https://docs.python.org/3/library/gettext.html#gettext.translation

**Comment by PetrDlouhy** [comment]
Hi @danilovmy I am maintainer of this project, but I don't use it any more. 
If you could provide an PR I will review it and merge.

**Comment by gcavalcante8808** [comment]
@danilovmy @PetrDlouhy I've created a PR addressing this: https://github.com/by-cx/InvoiceGenerator/pull/52 Can you review?

**Comment by PetrDlouhy** [comment]
Seems merged. I am closing the issue.

**Comment by danilovmy** [comment]
Thank you!
